# Generated by Django 4.1.1 on 2022-09-10 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 10, 0, 10, 5, 97736, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
