# Generated by Django 4.1.1 on 2022-09-10 01:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_posts_createdat_alter_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2022, 9, 10, 2, 5, 55, 435573)),
        ),
    ]
