# Generated by Django 4.1.1 on 2022-09-10 01:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_posts_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 1, 7, 32, 207859, tzinfo=datetime.timezone.utc)),
        ),
    ]
