# Generated by Django 4.1.1 on 2022-09-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_posts_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='createdAt',
            field=models.DateTimeField(),
        ),
    ]
