# Generated by Django 4.1.1 on 2022-09-15 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followers',
            old_name='follower_id',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='followers',
            old_name='user_id',
            new_name='user',
        ),
    ]
