# Generated by Django 4.1.1 on 2022-10-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_rename_follower_id_followers_follower_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='edited',
            field=models.BooleanField(default=False),
        ),
    ]
