# Generated by Django 4.1.1 on 2022-10-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_posts_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='editedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
