# Generated by Django 4.1.3 on 2022-11-27 19:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quadrants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[(1, 'Do First'), (2, 'Schedule'), (3, 'Delegate'), (4, "Don't do")], default='Do First', max_length=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='name',
        ),
        migrations.AddField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 19, 47, 50, 692155)),
        ),
        migrations.AddField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[(0, 'Done'), (1, 'In Progress')], default='In Progress', max_length=12),
        ),
        migrations.AddField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tasks',
            name='quadrant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='EisenHowerApp.quadrants'),
        ),
    ]
