# Generated by Django 4.1.3 on 2022-12-17 00:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 0, 1, 3, 506962, tzinfo=datetime.timezone.utc)),
        ),
    ]
