# Generated by Django 4.1.3 on 2022-11-27 20:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0002_quadrants_remove_tasks_name_tasks_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quadrants',
            name='name',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 20, 4, 38, 452256)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='quadrant',
            field=models.ForeignKey(choices=[(1, 'Do First'), (2, 'Schedule'), (3, 'Delegate'), (4, "Don't do")], null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='EisenHowerApp.quadrants'),
        ),
    ]
