# Generated by Django 4.1.3 on 2022-12-17 00:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0003_alter_tasks_created_at_alter_tasks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='description',
            field=models.TextField(default='No description', max_length=500),
        ),
        migrations.AddField(
            model_name='tasks',
            name='updated_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 0, 53, 28, 679068, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 0, 53, 28, 679068, tzinfo=datetime.timezone.utc)),
        ),
    ]
