# Generated by Django 4.1.3 on 2022-11-27 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0004_alter_quadrants_name_alter_tasks_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 20, 10, 23, 119761)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='quadrant',
            field=models.CharField(choices=[(1, 'Do First'), (2, 'Schedule'), (3, 'Delegate'), (4, "Don't do")], default=1, max_length=8),
        ),
        migrations.DeleteModel(
            name='Quadrants',
        ),
    ]
