# Generated by Django 4.1.3 on 2022-12-17 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0004_tasks_description_tasks_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 1, 39, 49, 180482, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 17, 1, 39, 49, 180482, tzinfo=datetime.timezone.utc)),
        ),
    ]
