# Generated by Django 4.1.3 on 2022-11-27 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0005_alter_tasks_created_at_alter_tasks_quadrant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 27, 20, 11, 18, 942595)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[(0, 'Done'), (1, 'In Progress')], default=1, max_length=12),
        ),
    ]
