# Generated by Django 4.1.3 on 2023-01-15 00:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0005_alter_tasks_created_at_alter_tasks_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='isUpdated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 0, 49, 47, 8751, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='updated_At',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 15, 0, 49, 47, 8751, tzinfo=datetime.timezone.utc)),
        ),
    ]
