# Generated by Django 4.1.3 on 2022-12-03 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0007_alter_tasks_created_at_alter_tasks_quadrant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 22, 20, 39, 230597, tzinfo=datetime.timezone.utc)),
        ),
    ]
