# Generated by Django 4.1.3 on 2022-12-04 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0008_alter_tasks_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 1, 53, 41, 990999, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='status',
            field=models.CharField(choices=[('done', 'Done'), ('in_progress', 'In Progress')], default='in_progress', max_length=13),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='title',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
