# Generated by Django 4.1.3 on 2022-12-07 00:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EisenHowerApp', '0010_alter_tasks_created_at_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='created_At',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 7, 0, 10, 3, 725306, tzinfo=datetime.timezone.utc)),
        ),
    ]
